### ISSUE TITLE
Add Parameters Selection to algorithms

### ISSUE THREAD

**Issue by Atyanar** [lukasjf/mphp#128]
- [x] add EA as algorithm with parameters k, m, n, normalization, fitness
- [x] for SFS add parameters k, m, n, normalization, fitness
- [x] set default k in all algorithms to 10
- [x] change name "considered features" to "excluded features"
- [x] normalizedFeatureSelection: merge into one algorithm with parameters substract, exlude (default!), and relief

**Comment by tamslo** [comment]
If no healthy tissue is selected, make algorithms that need healthy tissue not selectable

**Comment by tamslo** [comment]
If algorithm that does not use normalization is selected, do not consider healthy tissues (?)

**Comment by tamslo** [comment]
Keep `allAgainstRest` in mind
