### ISSUE TITLE
Find multiple feature subsets?

### ISSUE THREAD

**Issue by SebastianRehfeldt** [lukasjf/mphp#36]

**Comment by SebastianRehfeldt** [comment]
"Suppose a feature subset consists of age and gender resulted in a classifier with the
highest accuracy, say 74%; whereas another feature subset consists of age and body mass index (BMI) resulted in a classifier with a slightly lower accuracy, say 71%. The two factors in the first feature subset are both non-modifiable, whereas BMI in the second subset is 
 modifiable. Therefore, a clinician may be more interested in the second subset"

**Comment by lukasjf** [comment]
e.g. roulette for normalized feature selection
