### ISSUE TITLE
Evaluierung

### ISSUE THREAD

**Issue by tamslo** [lukasjf/mphp#4]
Ausbau der Evaluierung
* Classifier auf verschiedenen Datensets
* Clustering auf verschiedenen Datensets
* Abstand von Datenpunkten innerhalb Plots (kurz innerhalb Cluster, groß zwischen Clustern)
* Data for frontend plots
* Fitness functions

**Comment by SebastianRehfeldt** [comment]
* write function which returns aggregated evaluation results

**Comment by SebastianRehfeldt** [comment]
* return AUC from classifier
