### ISSUE TITLE
Show evaluation of result

### ISSUE THREAD

**Issue by Antje3** [lukasjf/mphp#49]

**Comment by SebastianRehfeldt** [comment]
{'LUAD-sick': ['low', 'mid-low', 'mid-high', 'mid-low', 'mid-low'],
 'THCA-sick': ['mid-high', 'low', 'mid-low', 'low', 'low'],
 'genes': ['"ENSG00000113396"',
           '"ENSG00000144481"',
           '"ENSG00000147689"',
           '"ENSG00000249395"',
           '"ENSG00000144481"']}
