### ISSUE TITLE
Enable multiple plots

### ISSUE THREAD

**Issue by Atyanar** [lukasjf/mphp#69]
For algorithms that compare multiple cancer types, it would be beneficial to show multiple plots - one clustering for healthy types, one for sick types, etc. in order to make the message more clear

**Comment by Atyanar** [comment]
Two Parts: First allow collapsing of tissue types into healthy / sick
Second allow detailed exploration of plots by selecting different tissue types / cancer types to display

**Comment by tamslo** [comment]
We don't need this anymore, do we?

**Comment by Atyanar** [comment]
No, we don't. :)
