### ISSUE TITLE
Add descriptions to frontend

### ISSUE THREAD

**Issue by Atyanar** [lukasjf/mphp#94]
Various things like the selected algorithms, their parameters, the Evaluation scores or the Gene results may not be understandable in one grasp. 
Here it would probably help to have a description box on hover/click/whatever that gives further information about the options.

**Comment by tamslo** [comment]
For description see [one against rest checkbox](https://github.com/lukasjf/mphp/commit/958be0355883e233e9850b3ca8b5fe38e080a5f2)

**Comment by Antje3** [comment]
- [x] Provide whole names of tissue types (maybe tooltip)
List of TCGA tissue types https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/sample-type-codes

**Comment by tamslo** [comment]
- [x] Es wäre noch cool, wenn wir eine Erklärung beim Result von oneAgainstRest hätten, dass man nun die Ergebnisse pro Cancer Type auswählen kann
